/* SAVRA / immersive rebrand study. Fictional data and local interactions only. */
const savra={world:null,kind:'',route:'',still:reduced(),camera:'orbit',explode:false,start:0,scrub:null,duration:6400};
const motionOff=()=>savra.still||reduced();
const svProgress=()=>!view.projected?0:motionOff()?1:savra.scrub??Spatial.clamp((performance.now()-savra.start)/savra.duration);
const mark=()=>`<svg viewBox="0 0 48 52" aria-hidden="true"><path class="mark-petal" fill="currentColor" d="M39 4C15-3 1 15 10 27c4 5 12 7 19 4C14 27 13 18 24 15c6-2 12-2 15-11Z"/><path class="mark-petal" fill="currentColor" d="M9 48c24 7 38-11 29-23-4-5-12-7-19-4 15 4 16 13 5 16-6 2-12 2-15 11Z"/></svg>`;
function svTitle(serial,kicker,words,copy=''){return `<header class="sv-chapter"><div class="overline"><span class="serial">${serial}</span>${kicker}</div><h1 class="kinetic" tabindex="-1">${words.map((w,i)=>`<span class="word ${w.startsWith('~')?'em':''}" style="--i:${i}">${w.replace(/^~/,'')}</span>`).join(' ')}</h1>${copy?`<p class="sv-deck">${copy}</p>`:''}`}
function svAnchor(id,text,cls=''){return `<div class="sv-anchor ${cls}" data-anchor="${id}">${text}</div>`}
function svLabels(kind){const a=DEMO.herd.find(a=>a.id===view.female),b=DEMO.bulls[view.bull];
 if(kind==='genetic')return svAnchor('mother',`<small>El origen</small><strong>${esc(a.name)} #${a.id}</strong>`)+svAnchor('bull',`<small>El aporte</small><strong>${b.name}</strong>`)+svAnchor('mother-data',a.a2||'SIN GENOTIPO','tag')+svAnchor('bull-data',b.a2,'tag')+svAnchor('calf','<small>Una nueva posibilidad</small><strong>Próxima generación.</strong>','calf');
 if(kind==='herd')return svAnchor('selected','#'+view.female+' · '+esc(a.name),'selected');
 if(kind==='market')return svAnchor('need','<small>Todo empieza acá</small><strong>Tu campo.</strong>')+(view.marketStep===2?DEMO.providers.map((p,i)=>svAnchor('provider-'+i,`<small>Conexión 0${i+1}</small><strong>${esc(p.name.split(' · ')[0])}</strong>`,'provider')).join(''):'');
 if(kind==='advisor')return DEMO.farms.map((f,i)=>svAnchor('farm-'+i,esc(f.name.replace('Tambo ','')),'farm')).join('');
 return kind==='plan'?svAnchor('document','<small>Decisiones que quedan</small><strong>Tu próximo paso.</strong>'):svAnchor('sheet','<small>El punto de partida</small><strong>293 posibilidades.</strong>');
}
function svMarket(){let right='';
 if(view.marketStep===1)right=`<form id="brief-form" class="sv-brief"><div class="sv-step"><b>02</b> Pongámosle forma</div><h2 class="sv-title-small">Esto entendimos.</h2><p class="brief-quote">${view.intent==='genetics'?'Querés mejorar los <mark>sólidos de tu tambo.</mark>':`Buscás <mark>${esc(view.brief.service.toLowerCase())}</mark> para <mark>${esc(view.brief.area)} hectáreas.</mark>`}</p>${view.intent==='machinery'?`<div class="sv-fields">${[['service','Trabajo'],['area','Hectáreas'],['zone','Zona'],['date','Cuándo']].map(([key,label])=>`<div class="sv-field"><label for="brief-${key}">${label}</label><input id="brief-${key}" name="${key}" value="${esc(view.brief[key])}" required ${key==='area'?'type="number" min="1"':''}></div>`).join('')}</div>`:'<p class="sv-deck">Cruza conecta tu rodeo con los aportes de cada toro. Empecemos por conocer tus animales.</p>'}<div class="actions">${button('Corregir','market-edit','text-btn')}<button class="btn primary" type="submit">${view.intent==='genetics'?'Seguir a Cruza':'Encontrar conexiones'} ${icon('arrow')}</button></div><p class="note" style="margin-top:16px">Interpretación predefinida para este ejemplo.</p></form>`;
 if(view.marketStep===2&&view.intent==='genetics')right=`<section class="sv-brief"><div class="sv-step"><b>03</b> Una nueva dirección</div><h2 class="sv-title-small">El futuro empieza<br>en tu rodeo.</h2><p class="sv-deck">Traé la planilla de ejemplo y explorá las combinaciones.</p><div class="actions">${link('Entrar a Cruza '+icon('arrow'),data.loaded?'/motor-genetico/matching/'+view.female:'/motor-genetico/importar','btn primary')}</div></section>`;
 if(view.marketStep===2&&view.intent==='machinery')right=`<section class="sv-results" aria-label="Conexiones disponibles"><div class="sv-step"><b>03</b> El territorio responde</div><div class="subtabs">${button('Disponibles · 3','available',view.unavailable?'':'active')}${button('Fuera de criterio · 3','unavailable',view.unavailable?'active':'')}</div>${view.unavailable?DEMO.unavailable.map(([name,reason],i)=>`<article class="sv-provider" style="--n:${i}"><h3>${name}</h3><p>${reason}</p></article>`).join(''):DEMO.providers.map((p,i)=>`<article class="sv-provider" style="--n:${i}"><span class="provider-index">0${i+1}</span><h3>${p.name}</h3><div class="facts">${p.distance} km · hasta ${p.capacity} ha · ${p.verification}</div><p>${p.reason}</p><div class="row between"><span class="small"><b>$${fmt(p.price)}</b> / ha</span>${button(view.requested.includes(i)?'Solicitud simulada ✓':'Conectar '+icon('arrow'),'request','compact',`data-index="${i}"`)}</div>${view.requested.includes(i)?`<div class="contact">Contacto ficticio: ${p.contact}</div>`:''}</article>`).join('')}<div class="row between" style="margin-top:14px">${button('Ajustar búsqueda','edit-brief','text-btn')}<span class="note">Disponibilidad y precios ficticios</span></div></section>`;
 return `<section class="sv-view view-market">${svTitle('01','CONEXIONES',view.marketStep===0?['El','campo','<br>','~te','conecta.']:['Una','idea.','<br>','~Mil','caminos.'],'Decí qué necesitás. Encontrá quién puede hacerlo posible.')}${view.marketStep===0?`<form class="sv-need" id="need-form"><label for="need">¿QUÉ QUERÉS PONER EN MOVIMIENTO?</label><textarea id="need" required>${esc(view.need)}</textarea><div class="row between"><span class="note">Empezá con una necesidad, en tus palabras.</span><button type="submit" class="action-orbit" aria-label="Explorar conexiones">${icon('arrow')}</button></div></form><div class="sv-examples">${button('Necesito maquinaria','example','','data-kind="machinery"')}${button('Quiero mejorar mi tambo','example','','data-kind="genetics"')}</div><p class="sv-market-economy">De una conversación a una conexión.<br><b>Ejemplo interactivo · sin solicitudes reales.</b></p>`:`<div style="margin-top:30px"><span class="sv-chip">${view.intent==='genetics'?'Genética / Cruza':esc(view.brief.zone)}</span></div>`}</header>${right}</section>`;
}
function svGenetic(){if(!data.loaded)return `<section class="sv-view view-genetic">${svTitle('02','CRUZA / EL ORIGEN',['El','futuro','<br>','~se','encuentra.'],'Cada cruce empieza con una historia. Traé tu rodeo y explorá lo que podría venir.')}<div class="sv-empty-cta">${link('Dar vida a mi rodeo '+icon('arrow'),'/motor-genetico/importar','btn primary')}</div><p class="sv-small-line">Una exploración genética, vaca por vaca.</p></header></section>`;
 const b=DEMO.bulls[view.bull],a=DEMO.herd.find(a=>a.id===view.female);
 return `<section class="sv-view view-genetic">${svTitle('02','CRUZA / ENCUENTRO GENÉTICO',['Un','origen.','<br>','~Otro','futuro.'],'Lo que ya tenés. Lo que querés aportar. Explorá el encuentro entre ambos.')}<div class="sv-goals" aria-label="Objetivo">${DEMO.goals.map((g,i)=>button(g,'goal',view.goal===i?'active':'',`data-index="${i}" aria-pressed="${view.goal===i}"`)).join('')}</div><div class="sv-candidates">${DEMO.orders[view.goal].map((idx,i)=>{const t=DEMO.bulls[idx];return `<button class="sv-candidate ${idx===view.bull?'active':''}" data-action="bull" data-index="${idx}" aria-pressed="${idx===view.bull}"><span>0${i+1}</span><span><strong>${t.name}</strong><small>${t.central} · ${t.a2}</small></span>${icon('arrow')}</button>`}).join('')}</div><div class="sv-genetic-links">${button('Un toro excluido','excluded','text-btn')}${link('Cambiar vaca ↗','/motor-genetico/tablero','text-btn')}</div><p class="sv-excluded-note">Orden ilustrativo por objetivo. Posición no equivale a probabilidad ni calificación genética.</p></header><div class="sv-genetic-stage-label">DOS HISTORIAS / UNA POSIBILIDAD</div>${view.projected?`<section class="sv-result" aria-label="Resultado de proyección"><div class="sv-step"><b>↗</b> El aporte de ${b.name}</div><h2>Lo que podría cambiar.</h2><p class="reason">${esc(b.reason)}. Escenario ilustrativo.</p><div class="metric"><span class="metric-label">Sólidos · grasa + proteína</span>${a.id==='084'?`<strong>6,8 → ${fmt(b.solids,1)}%</strong><div class="sv-mini-bars"><span>Madre / obs.</span><div class="track"><i style="width:68%"></i></div><span>6,8%</span><span>Cría / proy.</span><div class="track"><i class="projection" style="width:${b.solids*10}%"></i></div><span>${fmt(b.solids,1)}%</span></div><p class="note">Escala 0–10%. Fixture visual, sin motor conectado.</p>`:'<strong>No estimable</strong><p class="note">Sin sólidos observados para esta vaca.</p>'}</div><div class="metric"><span class="metric-label">A2 de la cría / consanguinidad</span><strong>No estimable</strong><p class="note">Madre ${a.a2||'sin dato'} · toro ${b.a2}. Faltan cálculo validado y pedigree completo.</p></div>${button('Ver fundamento','basis','text-btn')}</section>`:''}<div class="sv-projection-action">${view.projected?button('Guardar este encuentro '+icon('plus'),'add-plan','primary','id="add-plan"'):button('Explorar el encuentro '+icon('arrow'),'project','primary')}<div class="sv-sequence"><span class="seq-label">ORIGEN</span><label class="sr-only" for="sv-scrub">Recorrer el encuentro</label><input type="range" id="sv-scrub" min="0" max="100" value="${Math.round(svProgress()*100)}" ${view.projected?'':'disabled'}><output id="sv-progress">0%</output><span class="seq-label">FUTURO</span></div><p class="sv-genetic-note">Cría conceptual. La forma, el sexo y el pelaje no representan una predicción.</p></div></section>`;
}
function svHerdSide(){const animals=filteredAnimals(),a=DEMO.herd.find(a=>a.id===view.female);return `<aside class="sv-herd-side" id="herd-side"><div class="sv-step">Identidades / ${animals.length}</div><h2>Cada marca, una historia.</h2><div class="sv-animal-list">${animals.map(x=>`<button data-action="animal" data-id="${x.id}" class="${x.id===view.female?'active':''}"><span>#${x.id} ${x.id==='084'?'Aurora':''}</span><small>${labels[view.usual?x.usual:x.group]}</small></button>`).join('')||'<p class="note">Ningún animal coincide.</p>'}</div><div class="sv-animal-detail"><span class="eyebrow">Seleccionada / ${labels[view.usual?a.usual:a.group]}</span><h3>${esc(a.name)}<br><span class="muted">#${a.id}</span></h3><p>Genotipo ${a.a2||'sin dato'}<br>${a.id==='084'?'Sólidos observados 6,8%':'Sólidos: sin dato disponible'}</p>${link('Explorar su futuro '+icon('arrow'),'/motor-genetico/matching/'+a.id,'btn primary')}</div></aside>`}
function svHerdTable(){return `<div class="sv-herd-table" id="herd-table"><table><thead><tr><th>Animal</th><th>Destino</th><th>A2 observado</th><th>Selección</th></tr></thead><tbody>${filteredAnimals().map(a=>`<tr><td>#${a.id} · ${esc(a.name)}</td><td>${labels[view.usual?a.usual:a.group]}</td><td>${a.a2||'Sin dato'}</td><td>${button('Elegir','animal','compact',`data-id="${a.id}"`)}</td></tr>`).join('')}</tbody></table></div>`}
function svHerd(){if(!data.loaded)return svGenetic();return `<section class="sv-view view-herd">${svTitle('03','RODEO / UN PAISAJE DE DECISIONES',['<span class="number">293</span>','<br>','~historias','vivas.'],'Cada volumen conserva una identidad. Mové el criterio y seguí su recorrido.')}<div class="sv-group-nav">${Object.entries(labels).map(([key,label])=>`<button data-action="group" data-group="${key}" class="${view.filter===key?'active':''}"><strong id="count-${key}">${DEMO.herd.filter(a=>(view.usual?a.usual:a.group)===key).length}</strong>${label}</button>`).join('')}</div><div class="sv-herd-tools">${button(view.usual?'Ver propuesta':'Comparar con lo habitual','compare','ghost','id="compare"')}${button(view.table?'Volver al paisaje':'Ver tabla','table','ghost')}${button('Todos','group','ghost','data-group="all"')}<input class="sv-search" id="herd-search" aria-label="Buscar animal" placeholder="Buscar caravana o nombre" value="${esc(view.query)}"></div></header>${view.table?svHerdTable():''}${svHerdSide()}<div class="sv-herd-comparison"><strong>${view.usual?'Tu criterio habitual.':'Una nueva distribución.'}</strong><p>Sexado / Convencional / Carne. Tres destinos productivos.<br>Carne no representa animales fallados. Clasificación ficticia.</p></div></section>`}
function svImport(){return `<section class="sv-view view-import">${svTitle('00','ORIGEN / DE DATOS A POSIBILIDADES',['Una','planilla.','<br>','~Un','mundo.'],'Las filas se desprenden del papel. Cada una encuentra su lugar en el paisaje.')}<div class="sv-import-steps">${['ARCHIVO','COLUMNAS','RODEO VIVO'].map((t,i)=>`<span class="${view.importStep===i?'active':''}">0${i+1} / ${t}</span>`).join('')}</div></header>${view.importStep===0?`<div class="sv-import-actions" id="drop-zone">${button('Desplegar rodeo de ejemplo '+icon('arrow'),'sample','primary')}<p class="note">293 animales ficticios. El mockup usa un archivo de ejemplo; no lee ni sube archivos reales.</p></div>`:view.importStep===1?`<section class="sv-mapping"><div class="sv-step"><b>02</b> rodeo_ejemplo.xlsx</div><h2>Dale sentido a cada columna.</h2><table><thead><tr><th>Columna / ejemplo</th><th>Interpretación</th></tr></thead><tbody>${[['CARAVANA','#084'],['CSN2','A2/A2'],['SÓLIDOS','6,8%']].map(([name,example],i)=>`<tr><td>${name}<br><small class="muted">${example}</small></td><td><select aria-label="Interpretación de ${name}" data-map="${i}">${[['id','Identificación'],['a2','Genotipo A2'],['solids','Sólidos observados'],['ignore','No usar']].map(([v,l])=>`<option value="${v}" ${view.mapping[i]===v?'selected':''}>${l}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table><p id="mapping-error" class="error-text" role="alert"></p><div class="row between">${button('Volver','import-back','ghost')}${button('Darles vida '+icon('arrow'),'confirm-mapping','primary')}</div></section>`:`<div class="sv-import-complete"><h2>Ya están en movimiento.</h2><p>293 identidades, tres destinos. La planilla ahora se puede recorrer.</p><div class="row">${link('Entrar al rodeo '+icon('arrow'),'/motor-genetico/tablero','btn primary')}${button('Repetir','repeat-import','ghost')}</div></div>`}</section>`}
function svPlan(){return `<section class="sv-view view-plan">${svTitle('04','MI PLAN / DEL ENCUENTRO A LA ACCIÓN',['Mañana','<br>','~empieza','hoy.'],'Una idea se vuelve una decisión. Tu próximo paso queda acá.')}<p class="sv-small-line">${esc(activeFarm().name)} / documento de trabajo</p></header><section class="sv-plan-sheet"><div class="sv-plan-head"><span class="eyebrow">SAVRA / Encuentros guardados</span><h2>Lo que elegiste.</h2></div>${data.plan.length?`<table><thead><tr><th>Vaca</th><th>Aporte / central</th><th>Semen</th><th>Objetivo</th><th></th></tr></thead><tbody>${data.plan.map(p=>`<tr><td><strong>#${esc(p.femaleId)}</strong><br><small>${esc(p.femaleName)}</small></td><td><strong>${esc(p.bullName)}</strong><br><small>${esc(p.central)}</small></td><td>${esc(p.semen)}</td><td>${esc(p.goal)}</td><td>${button('Quitar','remove-plan','text-btn',`data-id="${p.femaleId}"`)}</td></tr>`).join('')}</tbody></table><div class="sv-plan-summary"><div><strong>${data.plan.length}</strong><span class="note"> / 293 vacas · ${293-data.plan.length} pendientes</span></div>${button('Llevar mi plan '+icon('download'),'export','primary')}</div><p class="note">Datos ficticios. Semen, parentesco y genotipos requieren revisión antes de cualquier uso real.</p>`:`<p class="sv-deck">Todavía no guardaste un encuentro. Explorá una combinación y volvé con una posibilidad.</p><div style="margin-top:25px">${link('Ir a Cruza '+icon('arrow'),'/motor-genetico/matching/'+view.female,'btn primary')}</div>`}</section></section>`}
function svAdvisorRows(){return sortedFarms().map(f=>`<div class="sv-farm-row ${view.selectedFarm===f.id?'active':''}" data-farm-row="${f.id}"><div><strong>${f.name.replace('Tambo ','')}</strong><small>${f.total} animales · ${f.total-f.known} sin genotipo</small></div><div class="proportion">${fmt(f.a2/f.known*100,1)}% A2<small>${f.a2} / ${f.known} genotipados</small></div><div class="pending">${f.total-f.planned}<small>pendientes</small></div>${button(view.selectedFarm===f.id?'Entrar ↗':'Explorar',view.selectedFarm===f.id?'open-farm':'select-farm','compact',`data-id="${f.id}"`)}</div>`).join('')}
function svAdvisor(){return `<section class="sv-view sv-advisor">${svTitle('05','PERSPECTIVA / ASESOR',['Diez','mundos.','~Una','mirada.'],'Cambiá el punto de vista. Descubrí dónde acompañar el próximo paso.')}</header><label class="sv-advisor-sort">Ordenar paisaje <select id="advisor-sort">${[['a2','Proporción A2'],['coverage','Cobertura de genotipos'],['pending','Pendientes del plan']].map(([v,l])=>`<option value="${v}" ${view.sort===v?'selected':''}>${l}</option>`).join('')}</select></label><div class="sv-advisor-table" id="advisor-rows">${svAdvisorRows()}</div><p class="sv-advisor-legend">Diez establecimientos ficticios. A2 se calcula sobre animales con genotipo disponible. Maquetas de tamaño decorativo; el dato está en cada fila.</p></section>`}
function svIdentity(){return `<section class="sv-view sv-placeholder">${svTitle('∞','UN NUEVO LENGUAJE',['El','campo','<br>','~en','movimiento.'],'SAVRA. Una marca que nace del encuentro entre la vida del campo y lo que todavía puede ser.')}<div style="margin-top:25px">${button('Explorar la identidad '+icon('arrow'),'concept','primary')}</div></header></section>`}
function svPlaceholder(){const name=route==='/ofertas'?'Mis ofertas':route==='/establecimiento'?'Mi lugar':'Conversaciones';return `<section class="sv-view sv-placeholder">${svTitle('↗',name.toUpperCase(),['Algo','nuevo','<br>','~está','creciendo.'],'Este espacio comparte la nueva identidad visual. Su funcionalidad queda pendiente en el recorrido conceptual.')}<div style="margin-top:25px">${link('Explorar conexiones '+icon('arrow'),'/mercado','btn primary')}</div></header></section>`}
function svState(){const s={empty:['Un','nuevo','~comienzo.','Cargá el ejemplo para recorrer las posibilidades.'],loading:['Todo','se','~conecta.','Estado de carga simulado.'],error:['Hagamos','otra','~pasada.','Error simulado para explorar la recuperación.'],'no-results':['Otro','camino','~espera.','Sin resultados para estos criterios de ejemplo.']}[view.demoState];return `<section class="sv-view sv-state">${view.demoState==='loading'?'<div class="loading-orbit" aria-hidden="true"></div>':''}${svTitle('↗','UN MOMENTO',[s[0],s[1],'<br>',s[2]],s[3])}<div style="margin-top:25px">${button('Volver al recorrido','normal','primary')}</div></header></section>`}
const svOldChat=chat;
chat=()=>svOldChat().replace('class="chat-shade"','class="sv-chat-shade"').replace('class="chat"','class="sv-chat"').replace('Preguntale a tus datos.','Tu rodeo tiene respuestas.');
function svShell(){return `<div id="savra-shell"><div class="sv-atmosphere" aria-hidden="true"></div><div class="sv-horizon" aria-hidden="true"><svg viewBox="0 0 1440 900" preserveAspectRatio="none">${Array.from({length:15},(_,i)=>`<path d="M-300 ${120+i*36} C 200 ${-170+i*43},720 ${950-i*22},1750 ${140+i*40}" style="animation-delay:-${i*1.7}s"/>`).join('')}</svg></div><div class="sv-grain" aria-hidden="true"></div><div class="sv-ticker" aria-hidden="true"><span>EL CAMPO EN MOVIMIENTO / EL CAMPO EN MOVIMIENTO / EL CAMPO EN MOVIMIENTO / </span></div><div class="sv-corner-index" aria-hidden="true">S</div><div id="world-layer"></div><div class="sv-travel" aria-hidden="true"></div><header class="sv-header"><a class="sv-brand" href="#/mercado" aria-label="SAVRA, ir a Conexiones">${mark()}<div><span class="sv-wordmark">savra</span><small>EL CAMPO EN MOVIMIENTO</small></div></a><span class="sv-header-center">Un mundo de posibilidades</span><div class="sv-header-actions"><span class="sv-studio-tag">CONCEPTO / 03</span><button class="sv-head-icon" data-action="sv-motion" aria-label="Pausar todo el movimiento" title="Pausar todo el movimiento">Ⅱ</button><button class="sv-account" data-action="sv-account"><span class="avatar">${isAdvisor()?'AS':'TE'}</span><span id="sv-farm">${esc(activeFarm().name.replace('Tambo ',''))}</span></button></div></header><nav class="sv-tabs" aria-label="Recorridos"></nav><main id="sv-main"><div id="main-content" tabindex="-1"></div></main><div class="sv-world-tools"><span>EXPLORÁ LA PERSPECTIVA</span><button data-action="sv-camera" aria-label="Cambiar cámara" title="Cambiar cámara">${icon('offers')}</button><button data-action="sv-explode" aria-label="Desarmar o reunir las facetas" title="Desarmar las facetas de la cría">${icon('genetics')}</button><button data-action="sv-home" aria-label="Restablecer perspectiva" title="Restablecer perspectiva">${icon('repeat')}</button></div><div class="sv-scroll-cue"><span></span>ARRASTRÁ EL PAISAJE · EXPLORÁ</div><footer class="sv-bottom"><div class="sv-bottom-note"><strong>SAVRA / ESTUDIO 03</strong><span>Datos ficticios · concepto interactivo</span></div><nav class="sv-nav" aria-label="Módulos"></nav><div class="sv-bottom-right">${button('Estudio','sv-studio')}${button('La marca ↗','concept')}</div></footer><div id="sv-chat-slot"></div></div>`}
function svKind(){if(route.includes('/matching'))return 'genetic';if(route.endsWith('/tablero'))return 'herd';if(route.endsWith('/importar'))return view.importStep===2?'herd':'import';if(route.endsWith('/asesor'))return 'advisor';if(route.endsWith('/plan'))return 'plan';return 'market'}
function svMountWorld(kind){const layer=$('#world-layer');if(kind!==savra.kind||!savra.world){savra.world?.dispose();savra.kind=kind;layer.innerHTML=`<canvas tabindex="0" aria-label="Paisaje 3D interactivo. Arrastrá para orbitar, flechas para mover y tecla Inicio para restablecer."></canvas>${svLabels(kind)}`;layer.className='entering';savra.world=new Spatial.World($('canvas',layer),kind,{reduced:motionOff,paused:motionOff,camera:()=>savra.camera,progress:svProgress,projected:()=>view.projected,explode:()=>savra.explode,found:()=>view.marketStep===2,imported:()=>route.endsWith('/importar')&&view.importStep===2,usual:()=>view.usual,selected:()=>view.female,filter:()=>view.filter,count:()=>data.plan.length,order:()=>sortedFarms().map(f=>DEMO.farms.findIndex(x=>x.id===f.id)),onSelect:id=>{view.female=id;view.projected=false;refreshHerd()},onFrame:()=>{$('[data-anchor="calf"]')?.classList.toggle('visible',view.projected&&svProgress()>.6);const range=$('#sv-scrub');if(range&&document.activeElement!==range)range.value=Math.round(svProgress()*100);if($('#sv-progress'))$('#sv-progress').textContent=Math.round(svProgress()*100)+'%'}});if(!savra.world.gl)layer.classList.add('no-webgl')}
 else{layer.querySelectorAll('.sv-anchor').forEach(el=>el.remove());layer.insertAdjacentHTML('beforeend',svLabels(kind))}
}
render=function(focus=false){if(!$('#savra-shell'))$('#app').innerHTML=svShell();const changed=savra.route!==route;savra.route=route;document.title='SAVRA — El campo en movimiento';document.documentElement.dataset.still=String(motionOff());const motor=route.startsWith('/motor-'),kind=svKind();
 const pending=['/establecimiento','/ofertas','/negociacion/matches'].includes(route);$('#savra-shell').dataset.chapter=pending?'placeholder':kind;
 const active=motor?2:route.startsWith('/negociacion')?3:route==='/mercado'?1:route==='/ofertas'?4:0;
 $('.sv-nav').innerHTML=[['Mi lugar','/establecimiento'],['Conexiones','/mercado'],['Cruza','/motor-genetico/matching/'+view.female],['Mi plan','/negociacion/plan'],['Mis ofertas','/ofertas']].map(([name,path],i)=>`<a href="#${path}" class="${i===active?'active ':''}${i===3?'plan-link':''}" ${i===active?'aria-current="page"':''}><span class="nav-num">0${i+1}</span>${name}${i===3&&data.plan.length?` · ${data.plan.length}`:''}</a>`).join('');
 $('.sv-tabs').innerHTML=tabs().map(([name,path],i)=>`<a href="#${path}" class="${route===path?'active':''}"><span class="tab-index">0${i+1}</span>${name.replace('Matching genético','Encuentros').replace('Tablero del rodeo','Rodeo vivo').replace('Carga del rodeo','El origen').replace('Panel del asesor','Perspectiva')}</a>`).join('')+(motor?button('Preguntá '+icon('chat'),'chat','compact',`aria-expanded="${view.chat}" aria-controls="chat-panel"`):'');
 let content;if(kind==='advisor'&&!isAdvisor())content=`<section class="sv-view sv-state">${svTitle('↗','PERSPECTIVA',['Una','mirada','~compartida.'],'Esta vista es para asesores. Tu rodeo está en Rodeo vivo.')}<div style="margin-top:25px">${link('Ir al rodeo','/motor-genetico/tablero','btn primary')}</div></header></section>`;else content=pending?svPlaceholder():view.demoState!=='normal'?svState():route==='/ui-kit'?svIdentity():kind==='genetic'?svGenetic():kind==='herd'&&!route.endsWith('/importar')?svHerd():route.endsWith('/importar')?svImport():kind==='plan'?svPlan():kind==='advisor'?svAdvisor():svMarket();
 $('#main-content').innerHTML=content;$('.sv-view')?.classList.add(changed?'arrive':'react');$('#sv-chat-slot').innerHTML=motor&&view.chat?chat():'';$('#sv-farm').textContent=activeFarm().name.replace('Tambo ','');$('.sv-account .avatar').textContent=isAdvisor()?'AS':'TE';const pause=$('[data-action="sv-motion"]');pause.textContent=motionOff()?'▶':'Ⅱ';pause.setAttribute('aria-label',motionOff()?'Reanudar movimiento':'Pausar todo el movimiento');pause.setAttribute('aria-pressed',String(motionOff()));$('[data-action="sv-explode"]').hidden=kind!=='genetic';svMountWorld(kind);
 if(changed){savra.camera='orbit';const wipe=$('.sv-travel');wipe.classList.remove('crossing');void wipe.offsetWidth;wipe.classList.add('crossing');window.scrollTo({top:0,behavior:'instant'})}if(focus)$('h1')?.focus({preventScroll:true});
};
refreshHerd=function(){if($('#herd-side'))$('#herd-side').outerHTML=svHerdSide();if($('#herd-table'))$('#herd-table').outerHTML=svHerdTable();const a=$('[data-anchor="selected"]');if(a)a.textContent='#'+view.female+' · '+DEMO.herd.find(x=>x.id===view.female).name;document.querySelectorAll('.sv-group-nav button').forEach(el=>el.classList.toggle('active',el.dataset.group===view.filter))};
compare=function(){view.usual=!view.usual;render()};
reorderAdvisor=function(){if($('#advisor-rows'))$('#advisor-rows').innerHTML=svAdvisorRows()};
const svOriginalAction=runAction;
runAction=function(action,el){
 if(action==='sv-motion'){savra.still=!savra.still;render();return}
 if(action==='sv-camera'){savra.camera={orbit:'top',top:'front',front:'orbit'}[savra.camera];toast('Perspectiva '+{orbit:'orbital',top:'cenital',front:'frontal'}[savra.camera]);return}
 if(action==='sv-home'){savra.camera='orbit';savra.world.drag=[0,0];return}
 if(action==='sv-explode'){if(!view.projected){toast('Explorá el encuentro para desplegar las facetas.');return}savra.explode=!savra.explode;return}
 if(action==='project'){savra.start=performance.now();savra.scrub=null;savra.explode=false}
 if(action==='repeat-import'){savra.world?.dispose();savra.world=null}
 if(action==='sv-account'){modal('Tu punto de partida',`<p>Cambiá de usuario o establecimiento ficticio para explorar el concepto.</p><div class="sv-fields"><div class="sv-field"><label for="user-select">Usuario demo</label><select id="user-select">${['tambero-a','tambero-b','asesor-1','admin'].map(u=>`<option ${user===u?'selected':''}>${u}</option>`).join('')}</select></div><div class="sv-field"><label for="farm-select">Establecimiento</label><select id="farm-select">${allowedFarms().map(f=>`<option value="${f.id}" ${farmId===f.id?'selected':''}>${f.name}</option>`).join('')}</select></div></div><p class="note">Las selecciones se guardan localmente por usuario y establecimiento.</p>`);return}
 if(action==='sv-studio'){modal('Explorá todos los estados',`<p>Un laboratorio para revisar el recorrido, los vacíos y la recuperación.</p><div class="sv-demo-options">${[['normal','Recorrido'],['empty','Vacío'],['loading','Cargando'],['error','Error'],['no-results','Sin resultados']].map(([v,l])=>button(l,'sv-state','',`data-state="${v}"`)).join('')}${button('Cargar 293 animales','sv-load')}${button('Reiniciar demo','reset')}${button('Guion de recorrido','guide')}</div><p class="note">Versión conceptual 03. Sin backend, IA ni solicitudes reales.</p>`);return}
 if(action==='sv-state'){view.demoState=el.dataset.state;closeModal();render();return}
 if(action==='sv-load'){closeModal();data.loaded=true;persist();render();toast('Rodeo de ejemplo disponible en Cruza.');return}
 if(action==='concept'){modal('Una marca que se mueve.',`<div class="sv-modal-brand sv-brand">${mark()}<span class="sv-wordmark">savra</span></div><p><b>El campo en movimiento.</b> Un nombre conceptual de sonido orgánico y un símbolo de dos corrientes que se encuentran. La marca expresa circulación, vínculo y crecimiento.</p><div class="sv-palette">${[['#091521','Tinta'],['#dcfa70','Citron'],['#ff8d72','Coral'],['#87d6c1','Menta'],['#edf0cf','Semilla']].map(([c,n])=>`<span style="background:${c};color:${c==='#091521'?'#edf0cf':'#091521'}">${n}</span>`).join('')}</div><dl><dt>El paisaje es la interfaz</dt><dd>Una escena 3D ocupa la pantalla. Las palabras y decisiones se distribuyen en su espacio.</dd><dt>Movimiento con intención</dt><dd>Atmósfera continua, contornos en circulación, entradas tipográficas, navegación suspendida, rutas de conexión y materia que se transforma.</dd><dt>Voz directa, cercana, activa</dt><dd>Conexiones: «Decí qué necesitás». Cruza: «Explorá el encuentro». Plan: «Lo que elegiste».</dd><dt>Rebranding conceptual</dt><dd>Mi establecimiento → Mi lugar. Mercado → Conexiones. Motor genético → Cruza. Negociación → Mi plan y conversaciones. Mis ofertas conserva su nombre.</dd></dl><p class="note">SAVRA es una propuesta creativa para AgroMatch, sin validación de disponibilidad comercial del nombre. Geometría original y datos ficticios. No es el desarrollo final.</p>`);return}
 return svOriginalAction(action,el);
};
document.addEventListener('input',e=>{if(e.target.id==='sv-scrub')savra.scrub=Number(e.target.value)/100});
document.addEventListener('change',e=>{if(e.target.id==='user-select'||e.target.id==='farm-select')closeModal()});
document.addEventListener('pointermove',e=>{if(motionOff())return;document.documentElement.style.setProperty('--sv-x',e.clientX+'px');document.documentElement.style.setProperty('--sv-y',e.clientY+'px')},{passive:true});
document.addEventListener('keydown',e=>{if(!e.target.matches('#world-layer canvas'))return;const directions={ArrowLeft:[-.12,0],ArrowRight:[.12,0],ArrowUp:[0,.08],ArrowDown:[0,-.08]};if(directions[e.key]){e.preventDefault();savra.world.drag[0]+=directions[e.key][0];savra.world.drag[1]+=directions[e.key][1]}else if(e.key==='Home'){e.preventDefault();savra.world.drag=[0,0]}});
matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>{savra.still=reduced();render()});
window.addEventListener('pagehide',()=>savra.world?.dispose());
render();
$('#savra-shell').insertAdjacentHTML('afterbegin',`<div class="sv-motes" aria-hidden="true">${Array.from({length:26},(_,i)=>`<i style="--px:${(i*37)%100}%;--py:${(i*23)%90}%;--s:${i%3+1}px;--d:${12+i%9}s;--delay:-${i*.9}s"></i>`).join('')}</div>`);
